title: Data Science Portfolio
description: Documenting my learning and projects in Data Science
theme: jekyll-theme-slate
show_downloads: false
github:
  is_project_page: false
social_links:
  github: https://github.com/isivaraj
  linkedin: https://linkedin.com/in/iniya-sivaraj
